### ISSUE TITLE
Great project BUT...

### ISSUE THREAD

**Issue by asigalov61** [lucasnfe/music-sentneuron#1]
Hey Lucas,

The project is great!!! Thank you! 

BUT...unfortunately, and strictly IMHO, I believe the project is unethical and its results can't and shouldn't be used for AI research.

I think that it is very wrong to control NNs by optimizing the values of specific neurons that are responsible for the sentiment signal. This is akin to brain surgery or mind control of sorts, which sorta defeats the whole purpose and benefits of NNs. Not to mention that it kinda reminds me of some unethical medical research practices.

Please feel free to disagree here as it is IMHO but I would love to hear your response and also I would be happy to elaborate more if you want.

Otherwise, your projects are very interesting and I also wanted to thank you specifically for adl-midi and vgmidis.

Sincerely,

Alex

**Comment by ymm-youbaba** [comment]
Hello friend, have you found this document——vgmidi/labelled/vgmidi_sent_train.csv？
