### ISSUE TITLE
Hellow,where is this document——vgmidi\\labelled\\vgmidi_sent_train.csv？

### ISSUE THREAD

**Issue by ymm-youbaba** [lucasnfe/music-sentneuron#4]

**Comment by lucasnfe** [comment]
To reproduce these results, you should the version 0.1 of the VGMIDI dataset, which can be downloaded as described in the README file:

`wget https://github.com/lucasnfe/vgmidi/archive/0.1.zip`

Once you unzip (`unzip 0.1.zip`) the dataset, you will find the `vgmidi_sent_train.csv` file at:

`vgmidi-0.1/labelled/vgmidi_sent_train.csv`

To get the right path, just rename the `vgmidi-0.1` directory to `vgmidi`.

**Comment by ymm-youbaba** [comment]
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lucasnfe/music-sentneuron"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 晚上11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lucasnfe/music-sentneuron] Hellow,where is this document——vgmidi\\labelled\\vgmidi_sent_train.csv？ (Issue #4)





 
To reproduce these results, you should the version 0.1 of the VGMIDI dataset, which can be downloaded as described in the README file:
 
wget https://github.com/lucasnfe/vgmidi/archive/0.1.zip
 
Once you unzip (unzip 0.1.zip) the dataset, you will find the vgmidi_sent_train.csv file at:
 
vgmidi-0.1/labelled/vgmidi_sent_train.csv
 
To get the right path, just rename the vgmidi-0.1 directory to vgmidi.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
